app/main/templates/review-submission.html

fixed typos

---

api/Dockerfile
api/aafrequest.py
api/const.py
api/views.py

Just adding a small change to test the process. The main purpose of the update is to handle errors a little better.

Added basic 500 error handling and logging to /var/log/aaf_api.log.

---

app/index.html
app/main/assets/css/aaf-36af1a.css
app/main/assets/js/aaf-36af1a.js
app/main/controllers/incidentInfo-ctrl.js
app/main/directives/limit-word-count-dir.js
app/main/templates/incidentInfo.html

incident info page is working with the service, validating the date field, and using Bobby's UI.

Incident info page 19 branch

---

app/main/templates/eligablePersonnel.html
app/main/templates/incidentInfo.html

closes #18
made a new pull request due to unintended merge

Eligible personnel page 18 branch

---

api/views.py

Small change to the search response with count of results and some pagination details. No pagination yet but this should allow us to build it into the response parsing now.

Quick wrapper for search. Will help with compatibility for pagination.

---

api/aafrequest.py
api/database.py
api/requirements.txt
api/views.py

Added the ability to provide pageNumber and perPage in the query string on a search request. The search response should now be able to assist in providing a paginated search display.
In addition, I changed the DB to connect through pymongo-flask. This provides a pool of connections that can be used across multiple requests instead creating a new connection each time.

Api search response and pagiantion

---

api/views.py

Added support for multiple documents in a single request.

Added support for an array of docs.

---

api/validate.py

Python 2 treats unicode as a distinct type from string. I ran into this issue but it looks like I only fixed it halfway.
Pushing a quick fix to this type.

Fixed str bug in validation schema

---

api/validate.py

Pushing fix to date input schema.

Fixed date to allow ISO date in adddtion to epoch time

---

api/validate.py

Fixing list vs Any() validation. Also, spelling counts.

Fixing schema types for permAddress and status. Fixing spelling

---

app/app.js
app/index.html
app/main/assets/css/aaf-36af1a.css
app/main/controllers/applicationStatus-ctrl.js
app/main/controllers/approver-home-ctrl.js
app/main/controllers/eligablePersonnel-ctrl.js
app/main/controllers/incidentInfo-ctrl.js
app/main/services/data-service.js
app/main/templates/applicationInformation.html
app/main/templates/approver-home.html
app/main/templates/eligablePersonnel.html
app/main/templates/home.html
app/main/templates/incidentInfo.html

updated schema changes and partially implemented admin home page

Approver home page 26

---

api/validate.py

Need to merge reviewDetails for admin review pages.

Added reviewDetails section to request.

---

app/app.js
app/main/controllers/incidentInfo-ctrl.js
app/main/templates/attachments.html
app/main/templates/navigation.html
app/main/templates/review-submission.html

made sure incident date gets populated and added attachments to the side nav

Misc bugs - incident date and side nav

---

api/aafrequest.py
api/const.py
api/test.py
api/validate.py
api/views.py

Not 100% satisfied but tested and working right now. Will review and improve but pushing now due to timeframe.

Added status change actions. Need to review/test.

---

app/main/controllers/other-ctrl.js
app/main/templates/applicationInformation.html
app/main/templates/assistanceRequest.html
app/main/templates/attachments.html
app/main/templates/eligablePersonnel.html
app/main/templates/incidentInfo.html
app/main/templates/other.html
app/main/templates/review-submission.html

closes #58 
added fieldset validation to disable inputs if the applications is not in 'draft' or 'returned' status

Application not editable 58

---

app/index.html
app/main/assets/css/aaf-36af1a.css
app/main/controllers/applicationStatus-ctrl.js
app/main/controllers/approvePage-ctrl.js
app/main/controllers/approver-application-ctrl.js
app/main/controllers/approver-deny-ctrl.js
app/main/controllers/approver-home-ctrl.js
app/main/controllers/return-modal-ctrl.js
app/main/controllers/review-submission-ctrl.js
app/main/services/data-service.js
app/main/templates/approver-application.html
app/main/templates/approver-home.html
app/main/templates/home.html

closes #83 
updates status and status bar

Status calls 83

---

app/main/assets/css/aaf-36af1a.css
app/main/controllers/applicationInformation-ctrl.js
app/main/templates/home.html

#89: will only call create app once now, fixed so viewing app after submission won't create new one
closes #89

Multiple app bug

---

app/index.html
app/main/assets/css/aaf-36af1a.css
app/main/templates/admin-navigation.html
app/main/templates/approver-application.html

#91: added updates based on Brooke's feedback
closes #91

UI Updates

---

app/main/templates/applicationInformation.html

#76: fixed the tabindex for the app info page (really the only page that needed it)

misc bug fixes

---

app/main/assets/css/aaf-36af1a.css
app/main/templates/approver-home.html
app/main/templates/assistanceRequest.html
app/main/templates/attachments.html
app/main/templates/navigation.html

#98: added backwards nav and fixed footer position

---

app/main/controllers/attachments-ctrl.js
app/main/directives/attachments-dir.js
app/main/templates/attachments.html

attachments page fix for duplicate uploads and page reload issues

attachments page fix for duplicate uploads and refresh issues

---

api/aafrequest.py
api/config.py
api/database.py
api/views.py

Application document route now accepts DELETE

Api delete doc and cleanup

---

app/index.html
app/main/templates/home.html

102: edited redirects for donate button and login button

---

api/views.py
app/main/controllers/approvePage-ctrl.js
app/main/controllers/approver-deny-ctrl.js
app/main/services/data-service.js
app/main/templates/approvePage.html
app/main/templates/approver-deny.html

117: added admin dropdown for approve and deny pages

---

api/aafrequest.py
api/database.py
api/export.py
api/ldap.py
api/validate.py
api/views.py
configs/templates/Approved.html
configs/templates/Denied.html

Merging CSV export and email changes.

Api ldap and export
